name: MineBedWars
version: 1.0
author: LoreSchaeffer && TheDarkSword01
main: it.mineblock.minebedwars.Main
description: Just another bedwars plugin
depend: [MBCore]

commands:
  mbw:
    aliases: [minebedwars, mbedwars, mbwars]
    descripiton: Main command of this plugin
  mbwreload:
    aliases: [mbwr]
    description: Reload this plugin